version: "3"
services:
  ownfoil:
    container_name: OwnFoil
    image: a1ex4/ownfoil:latest
    environment:
      # For write permission in config directory
      - PUID=1026
      - PGID=101
      # to create/update an admin user at startup
      - USER_ADMIN_NAME=USUARIO # cambiar usuario para GUIWEB de configuracion
      - USER_ADMIN_PASSWORD=CONTRASEÑA # cambiar contraseña para GUIWEB de configuracion
      # to create/update a regular user at startup
      # - USER_GUEST_NAME=guest
      # - USER_GUEST_PASSWORD=oerze!@8981
    volumes:
      - /volume3/Nintendo Switch/Juegos:/games # ruta de la carpeta donde tengas los juegos de la Switch
      - ./config:/app/config # crear antes las carpetas para la instalacion
      - ./data:/app/data # crear antes las carpetas para la instalacion
    ports:
      - "8465:8465"
